### ISSUE TITLE
module initialization error - subscriptions-transport-ws - Amazon lambda

### ISSUE THREAD

**Issue by delta98** [graphcool/prisma-binding#101]
I have written a lambda function which is using `prisma-binding` to create new instances of a type `Snippet`

```
Prisma.mutation.createSnippet({ 
data: {
    title: article.title,
    featuredImage: article.urlToImage,
    summary: article.description,
    publishedAt: article.publishedAt,
    url: article.url,
    source: {
        connect: { slug: article.source.id }
   }
}})
```

The instance is setup using the following:

```
import { Prisma } from '../generated/prisma'

export default new Prisma({
    endpoint: process.env.PRISMA_ENDPOINT,
    debug: false,//(process.env.NODE_ENV !== 'production'),
    secret: process.env.PRISMA_SECRET
})
```

The result when executing via a GET request to the lambda url or when using a scheduler event is:

```
module initialization error: Error
at Error (native)
at Object.fs.openSync (fs.js:641:18)
at Object.fs.readFileSync (fs.js:509:33)
at Object.Module._extensions..js (module.js:578:20)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/subscriptions-transport-ws/dist/client.js:19:27)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
```

I don't believe this is an intended result.

**Comment by timsuchanek** [comment]
Thanks for reporting @delta98 ! Are you using something like serverless to host the function?
We are running prisma-binding successfully in lambda through `up`.
Another question: Are you using typescript?
Thanks!

**Comment by delta98** [comment]
hey @timsuchanek using serverless and typscript, would you be able to share your config through `up`? It's a scheduled task.

**Comment by delta98** [comment]
I've carried out some further investigation. Taking the bundled zip which is sent to AWS, running it on the command line, it runs successfully. But not within the lambda env.

**Comment by delta98** [comment]
It may also be due to Node.js 6.10 being default for serverless... will update default engine and report back.

**Comment by delta98** [comment]
This was a local build issue caused by the way npm builds for local binaries, there are 2 potential solutions:

1) Use[ serverless-plugin-optimize](`https://github.com/FidelLimited/serverless-plugin-optimize`) which will compile and browsify your code - thus not requiring node_modules - smaller binary to upload too 🙏 
2) Use docker to precompile the node modules similar to https://github.com/graphcool/serverless-image-proxy

Either resolve this issue, which could be caused by a bad binary or permissions locally affecting the AWS lambda env.
