### ISSUE TITLE
Stalled data, global usage of http-link-loader and facebook data loader

### ISSUE THREAD

**Issue by nickluger** [graphcool/prisma-binding#106]
This issue might be also caused by a misuse by `prisma-binding`.

https://github.com/graphcool/http-link-dataloader/issues/3

**Comment by nickluger** [comment]
Was a problem with `http-link-dataloader` indeed.

**Comment by hoodsy** [comment]
@nickluger do you have a solution for this issue? I've been tracking over here: https://github.com/graphcool/prisma-binding/issues/106

**Comment by nickluger** [comment]
Not really, you could create a new `prisma-binding` instance for the second request, which will contain a new instance of the `http-link-dataloader` (with empty cache), instead of using the prisma instance passed in the request. 

```ts
// instead of this
ctx.db.query.posts({...})
// this
getPrismaLink().query.posts({...})

// create a new prisma binding instance on demand
export const getPrismaLink = (debug: boolean = false) => new Prisma({
  endpoint: requiredEnvVars.PRISMA_ENDPOINT
  secret: requiredEnvVars.PRISMA_SECRET, 
  debug: debug 
})
```

**Comment by hoodsy** [comment]
thanks! I'm going to give this a shot.

**Comment by ramsaylanier** [comment]
@nickluger I can confirm that this solution works.
