### ISSUE TITLE
Please update graphql dependency to 0.13.1

### ISSUE THREAD

**Issue by steida** [graphcool/prisma-binding#111]
graphql 13.0.0 is broken

https://github.com/este/este/issues/1466#issuecomment-366383204

Btw, why the lib has fixed dependencies? It should follow semver imho.

**Comment by steida** [comment]
Ok, I think I got it. Please use ^ in your graphcool/* dependencies. It's fixed in multiple places having fixed dependencies breaks everything.

**Comment by schickling** [comment]
I've now moved `graphql` to `peerDependencies`, so it should work for you.

**Comment by steida** [comment]
@schickling Finally 😂 Thank you.
