### ISSUE TITLE
Params are not being passed through via forwardTo('db')

### ISSUE THREAD

**Issue by k00k** [graphcool/prisma-binding#127]
When using `forwardTo('db')` to pass a db query through to the `graphql-yoga` server, the params available on the db side aren't made available on the yoga side.

For example, from `Query.ts`:

```import { getUserId, Context } from '../utils/auth'
import { forwardTo } from 'prisma-binding'

export const Query = {
  grades: forwardTo('db'),
...
}
```

The following query will work fine in the Playground when using the db (Prisma Cloud), but not when using our graphql-yoga endpoint:

```
query {
    grades(orderBy: number_ASC) {
      games {
        id
      }
      longname
      number
      shortname
      url
    }
  }
```
Error message received: 
```
{
  "errors": [
    {
      "message": "Unknown argument \"orderBy\" on field \"grades\" of type \"Query\".",
      "locations": [
        {
          "line": 2,
          "column": 12
        }
      ]
    }
  ]
}
```
Here's a video screen cap of it in action: https://streamable.com/017m6

Expected behavior: Params are passed directly through to the db's graphql server.

**Comment by marktani** [comment]
Can you share the definition for the `grades` query in your application server's `schema.graphql`?

**Comment by k00k** [comment]
From `schema.graphql`:

```
# import Game, GameCreateInput, Grade from "./generated/prisma.graphql"
type Query {
  grades: [Grade]
  ...
}
```

**Comment by marktani** [comment]
Ah, that's probably the explanation. Please try this instead:

```graphql
# import Game, GameCreateInput, Grade, GradeOrderByInput, GradeWhereInput from "./generated/prisma.graphql"
type Query {
  grades(where: GradeWhereInput, orderBy: GradeOrderByInput): [Grade]
  ...
}
```

Note that if you want to add more inputs like `skip` or `first`, you need to add them to this query declaration in a similar fashion.

I expect this problem to be resolved with this adjustment, let me know if that's not the case 🙂

**Comment by k00k** [comment]
Yes, that was it, works as expected now. Feel free to close this issue.

**Comment by marktani** [comment]
Great!

**Comment by lionstone** [comment]
I'm having the same issue. Does this mean that I have to manually declare the all those imports for each resolver I'm forwarding? Feels like the kind of boilerplate I'm trying to avoid by using `forwardTo('db')` in the first place unless i'm mis-understanding?

**Comment by DamianPereira** [comment]
@lionstone , I had the same problem, but I found a solution. You can actually import queries from prisma.graphql like this:

`# import Query.posts from "./generated/prisma.graphql"`

Then in your resolver you just do `posts: forwardTo('db')`

This exposes the posts query from prisma to the world, without having to write schema twice.

**Comment by sundarkandasamy** [comment]
s
