### ISSUE TITLE
Querying Enum Values From Prisma Context 

### ISSUE THREAD

**Issue by dsoraluz-carecloud** [graphcool/prisma-binding#140]
Question for you guys, is there a way to return the enumerated values for a custom type in a query using the context object in Prisma?

The query in the playground looks like the following:

```
{
    __type(name: "UserRole") {
        enumValues {
            name
        }
    }
}
```

But I am having trouble achieving it through the context object query.

I would imagine there would be something like...

`ctx.db.query.__type({enumValues: "UserRole"})` 

but there doesnt seem to be. Can anyone lend some guidance to a workaround ?

**Comment by marktani** [comment]
Hey @dsoraluz-carecloud, thanks for bringing this up!

As far as I know, the `__type` query is not available on `ctx.db.query` - I don't see a reason why we shouldn't add it though!

The [`ctx.db.request`](https://github.com/graphcool/prisma-binding#request) presents a good approach to accomplish what you want - it looks like this:

```js
const query = `
  query {
    __type(name: "UserRole") {
      enumValues {
        name
      }
    }
  }
`

const variables = { }

prisma.request(query, variables)
  .then(result => console.log(result))
```

**Comment by dsoraluz-carecloud** [comment]
Just tested this and it works  but having the `__type` query on `ctx.db.query` would be a useful addition.

**Comment by marktani** [comment]
For anyone interested to provide a PR for this, this would be added to [`graphql-binding`](https://github.com/graphql-binding/graphql-binding).

**Comment by schickling** [comment]
I really like the idea of adding `query.__type` to the underlying graphql binding. Can you open a issue for this @dsoraluz-carecloud?

**Comment by dsoraluz-carecloud** [comment]
Sure thing, I will open an issue now.
