### ISSUE TITLE
Doing a query in resolvers without specifing a fragment omits object properties?

### ISSUE THREAD

**Issue by goncy** [graphcool/prisma-binding#74]
Passing this fragment:
```graphql
{
  id
  name
  description
  direction
  locations
  price
  spaces
  operation
  categories
  expenses {
    name
    price
  }
  images
  amenities {
    description
    icon
    type
  }
  featured
  summary {
    name
    value
  }
}
```

To this resolver:
```javascript
registriesByQuery: async (parent, {query}, ctx) => {
    const registries = await ctx.db.query.registries({where: {operation: query.operation}}, FullRegistry) // <- Fragment here
    console.log(registries) // Returns the object below
  },
```

Returns the full object, that's fine:

```graphql
  {
      "locations": [
        "zona sur",
        "quilmes",
        "bernal",
        "bernal este"
      ],
      "name": "Caseros 754",
      "description": "Casa 5 ambientes en Barrio Parque",
      "price": 250000,
      "featured": false,
      "direction": "Caseros 754, Barrio Parque, Bernal",
      "id": "cjcknlka700e201288tk49410",
      "operation": "venta",
      "amenities": [
        {
          "description": "3 dormitorios",
          "icon": "fa fa-bed",
          "type": "spaces"
        },
        {
          "description": "1 baño",
          "icon": "fa fa-bath",
          "type": "spaces"
        },
        {
          "description": "1 toilette",
          "icon": "fa fa-bath",
          "type": "spaces"
        },
        {
          "description": "Equipada",
          "icon": "fa fa-cutlery",
          "type": "spaces"
        },
        {
          "description": "Jardín",
          "icon": "fa fa-leaf",
          "type": "spaces"
        }
      ],
      "categories": [
        "casa"
      ],
      "images": [
        "http://placehold.it/256x256"
      ],
      "spaces": 3,
      "summary": [
        {
          "name": "Superficie cubierta",
          "value": "123 M2"
        }
      ],
      "expenses": []
    }
```

But if i don't pass the fragment, I got this back (missing all the fields that are arrays or nested):

```graphql
{ id: 'cjcknlka700e201288tk49410',
    createdAt: '2018-01-18T15:31:06.000Z',
    updatedAt: '2018-01-18T15:31:06.000Z',
    name: 'Caseros 754',
    description: 'Casa 5 ambientes en Barrio Parque',
    direction: 'Caseros 754, Barrio Parque, Bernal',
    price: 250000,
    spaces: 3,
    operation: 'venta',
    featured: false }
```

I'm sure that i'm missing something but it would be nice to know what, thanks!

**Comment by marktani** [comment]
Hey @goncy, can you tell me how exactly you are passing in the fragment into the resolver?

I think all of this is actually expected behaviour, but it's not as straight-forward the first time you encounter it.

I mapped out the different behaviours of resolvers, depending on whether or not you're providing an `info` object [here](https://www.graph.cool/forum/t/querying-specific-fields-in-db-from-localservice-in-graphcool-1-0/2075/4?u=nilan). Let me know if that resolvers your question, or if you are encountering a different situation! 🙂

**Comment by goncy** [comment]
First of all thanks!, this is what i'm passing as fragment

![image](https://user-images.githubusercontent.com/6494462/35114891-2ac33a96-fc65-11e7-8a24-c063b550210a.png)

So, if i replace the fragment with the info variable comming after context in the resolver the result should be the same?

**Comment by goncy** [comment]
Oh, i think i got it, if you provide the info field you will get just the information from the original query, if you don't provide anything you will get the scalar fields, otherwise if you provide a fragment or different schema, you will get that back, something like that?

**Comment by kbrandwijk** [comment]
@goncy That's exactly how it works.
