### ISSUE TITLE
Calling prisma after altering field has no effect when the info object is passed.

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-binding#88]
@Fonz001 commented on [Tue Jan 30 2018](https://github.com/graphcool/prisma/issues/1774)

**Current behavior**

Calling prisma after altering field has no effect when the info object is passed.

**Reproduction**

1. I have a simple Post model, matching with the typescript boilerplate from prisma init. 
2. Copied the endpoint: `createPost(data: PostCreateInput!): Post!` from `prisma.graphql`
3. Implemented the resolver:

```
  async createPost(parent, args: { data: PostCreateInput }, ctx: Context, info) {
    const userId = getUserId(ctx)
   
    // Alter the title, we want it to be uppercase
    if (args.data.title) args.data.title = args.data.title.toUpperCase()

    // Double check
    console.log(args)

    // Pass the call to prisma
    return ctx.db.mutation.createPost(args, info)
  }
```

**Expected behavior?**

I expect to see the title to uppercase in the console. However, I see the original title being passed:

```
{ data: { title: 'FOO2', text: 'bar2', author: { connect: [Object] } } }
Request to https://eu1.prisma.sh/patrick-van-rietschoten/prisma-temp/dev:
query:
mutation {
  createPost(data: {title: "foo2", text: "bar2", author: {connect: {id: "cjd1br6zytcsv0113pp0xbnlk"}}}) {
    id
  }
}
operationName: null
variables:
{}
Response from https://eu1.prisma.sh/patrick-van-rietschoten/prisma-temp/dev:
{
  "createPost": {
    "id": "cjd1c6nvcukn80113rjfcprx1"
  }
}
```

**Extra info:**

Excluding the `info` parameter from the prisma call results in the expected behavior:

`ctx.db.mutation.createPost(args)`

```
{ data: { title: 'FOO2', text: 'bar2', author: { connect: [Object] } } }
Request to https://eu1.prisma.sh/patrick-van-rietschoten/prisma-temp/dev:
query:
mutation ($_data: PostCreateInput!) {
  createPost(data: $_data) {
    id
    createdAt
    updatedAt
    isPublished
    title
    text
  }
}
operationName: null
variables:
{
  "_data": {
    "title": "FOO2",
    "text": "bar2",
    "author": {
      "connect": {
        "id": "cjd1br6zytcsv0113pp0xbnlk"
      }
    }
  }
}
Response from https://eu1.prisma.sh/patrick-van-rietschoten/prisma-temp/dev:
{
  "createPost": {
    "updatedAt": "2018-01-30T07:45:27.000Z",
    "isPublished": false,
    "text": "bar2",
    "id": "cjd1c8yk4urma0113d2xpbtu1",
    "createdAt": "2018-01-30T07:45:27.000Z",
    "title": "FOO2"
  }
}
```

**Comment by marktani** [comment]
Hey @Fonz001, thanks for bringing this up, I expect it is an underlying issue in [graphql-tools](https://github.com/apollographql/graphql-tools/), but need to verify this.

Can you try some of the following and see if that resolves the problem?

* rename `data` in `schema.graphql` to `data2`
* replace `return ctx.db.mutation.createPost(args, info)`  by `return ctx.db.mutation.createPost({...args}, info)`

**Comment by Fonz001** [comment]
> rename data in schema.graphql to data2

Works! I will use this as a quick fix for now.

> replace return ctx.db.mutation.createPost(args, info) by return ctx.db.mutation.createPost({...args}, info)

Doesn't work!

**Comment by marktani** [comment]
Thanks, looks like the same as https://github.com/graphcool/prisma-binding/issues/73 (somehow didn't find it before). Closing this one 🙂
