### ISSUE TITLE
Export typeDefs from generated prisma.ts

### ISSUE THREAD

**Issue by ojkelly** [graphcool/prisma-binding#91]
Hi,

I would like to be able to access `typedefs` in the generated `prisma.ts` file.

Specifically changing the generated file from:

```
const typeDefs = `
# THIS FILE HAS BEEN AUTO-GENERATED BY "PRISMA DEPLOY"
# DO NOT EDIT THIS FILE DIRECTLY
...
`
```

to:

```
export const typeDefs = `
# THIS FILE HAS BEEN AUTO-GENERATED BY "PRISMA DEPLOY"
# DO NOT EDIT THIS FILE DIRECTLY
...
`
```

I'm happy to make a PR if this is something that would be accepted, and someone can point me in the right direction.

**Comment by kbrandwijk** [comment]
Yes, that seems like a great addition! Can you move this issue to https://github.com/supergraphql/graphql-static-binding, and if you want to submit a PR, that would be highly appreciated 🙏
